// <auto-generated />
using System;
using Embaixadinha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Embaixadinha.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230131002006_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Embaixadinha.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2023, 1, 30, 21, 20, 6, 289, DateTimeKind.Local).AddTicks(2068))
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("Updated_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2023, 1, 30, 21, 20, 6, 289, DateTimeKind.Local).AddTicks(2401))
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_name");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("Embaixadinha.Models.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2023, 1, 30, 21, 20, 6, 289, DateTimeKind.Local).AddTicks(7464))
                        .HasColumnName("created_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("Updated_At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2023, 1, 30, 21, 20, 6, 289, DateTimeKind.Local).AddTicks(8240))
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_score");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_score_player_id");

                    b.ToTable("score", (string)null);
                });

            modelBuilder.Entity("Embaixadinha.Models.Entities.Score", b =>
                {
                    b.HasOne("Embaixadinha.Models.Entities.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Embaixadinha.Models.Entities.Player", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
