// <auto-generated />
using System;
using Embaixadinha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Embaixadinha.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230131124056_AddUniqueConstraintPlayerIp")]
    partial class AddUniqueConstraintPlayerIp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Embaixadinha.Models.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("PlayerIp")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("player_ip");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_player_name");

                    b.HasIndex("PlayerIp")
                        .IsUnique()
                        .HasDatabaseName("ix_player_player_ip");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("Embaixadinha.Models.Entities.Score", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_score");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_score_player_id");

                    b.ToTable("score", (string)null);
                });

            modelBuilder.Entity("Embaixadinha.Models.Entities.Score", b =>
                {
                    b.HasOne("Embaixadinha.Models.Entities.Player", "Player")
                        .WithMany("Scores")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_score_player_player_id");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Embaixadinha.Models.Entities.Player", b =>
                {
                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
